RegisterCommand("openUIWeed", function()
    SetNuiFocus(true, true)
    StartScreenEffect('CamPushInFranklin', 0, false)
    Wait(1000)
    SetTimecycleModifier("hud_def_blur")
    SetTimecycleModifierStrength(0.9)
    SendNUIMessage({action = "show", health = 30, water = 10, id = 4})
end)

RegisterCommand("debugWeed", function()
    StopScreenEffect('CamPushInFranklin')
    ClearTimecycleModifier()
    SetNuiFocus(false,  false)
    SendNUIMessage({action = "hide"})
end)

RegisterNUICallback('NUIFocusOff', function()
    StopScreenEffect('CamPushInFranklin')
    ClearTimecycleModifier()
    SetNuiFocus(false, false)
end)

RegisterNUICallback("updateWater", function(data)
    TriggerServerEvent("xWeed:arroserPlant", data.id)
end)

RegisterNUICallback("removePlant", function(data)
    TriggerServerEvent("xWeed:removePlant", data.id)
end)